### ISSUE TITLE
Add Google App Engine

### ISSUE THREAD

**Issue by NdagiStanley** [NdagiStanley/python-deployed#3]
Here's an example of an `app.yaml` for this:

```yaml
runtime: python
env: flex

runtime_config:
    python_version: 3

entrypoint: gunicorn hello:app --log-file - --bind 0.0.0.0:80

```
